spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      path: /db

  devtools:
    livereload:
      enabled: true

  jpa:
    deferDatasourceInitialization: true
    open-in-view: false