server:
  port: 8080

spring:

  rabbitmq:
    username: guest
    password: guest
    host: broker
    port: 5672

  redis:
    host: redis
    port: 6379

  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true
      path: /db

  devtools:
    livereload:
      enabled: true

  jpa:
    deferDatasourceInitialization: true
    open-in-view: false