spring:
  config:
    activate:
      on-profile: test
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb

  devtools:
    livereload:
      enabled: true

  h2:
    console:
      enabled: true
      path: /db